services:
  db:
    image: postgres:latest
    ports:
      - 4000:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: eshop
    container_name: eshop-db